import Order from "./Order";

export default class OrderRepository {
    public save(order: Order): string{
        //Pretend to save something and return id generated by DB
         return "order_id" + Math.random();
    }
}